show databases;
CREATE DATABASE mydatabase;
CREATE TABLE PERSONS(PERSONID INT, FNAME VARCHAR(10), LNAME VARCHAR(10), CITY VARCHAR(10)); 
USE MYDATABASE;
SHOW TABLES;
INSERT INTO PERSONS(PERSONID,FNAME,LNAME,CITY) VALUES(01,"SHUBHAM","SIRSAT","AKOLA");
SELECT * FROM PERSONS;

